let test = document.getElementById("mydiv");
test.style.backgroundColor = "yellow";
test.style.color = "blue";
test. style.margin = "20px";
test.style.padding = "20px";
test.style.fontSize = "18px";
test.style.fontWeight = "bold";
test.style.height = "200px";
test.style.width = "300px";
